### ISSUE TITLE
Error reading in patent.tsv

### ISSUE THREAD

**Issue by REAnalytics** [CSSIP-AIR/PatentsView-Code-Snippets#8]
I tried using your R snippet to read patent.tsv:

data<- read.delim(unz("patent.tsv.zip", "patent.tsv"), header=TRUE, sep ="\t", comment.char="#",  stringsAsFactors = FALSE, quote="", fill = FALSE)

which generates this error:
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 2353 did not have 11 elements

I can only get it to work by changing fill to TRUE.

**Comment by ckjohnson7** [comment]
edited to now set fill=TRUE
